/**
 * Tests for output/viz/lib/lockfile-parsers.js
 *
 * All fixtures are inline strings to avoid file I/O.
 * Each parser returns Array<{name, version, deps, ecosystem}>.
 */

const LP = require('../../output/viz/lib/lockfile-parsers.js');

// ── Helpers ──────────────────────────────────────────────────────────────────

function pkg(list, name) { return list.find(p => p.name === name || p.name.includes(name)); }
function names(list) { return list.map(p => p.name); }

// ─────────────────────────────────────────────────────────────────────────────
// package-lock.json (npm v2)
// ─────────────────────────────────────────────────────────────────────────────
describe('parsePackageLockJson', () => {
  const fixture = JSON.stringify({
    name: 'my-app', version: '1.0.0', lockfileVersion: 2,
    packages: {
      '': { name: 'my-app', version: '1.0.0' },
      'node_modules/lodash': { version: '4.17.21', resolved: 'https://r.tgz' },
      'node_modules/express': { version: '4.18.2', dependencies: { lodash: '^4.0.0' }, peerDependencies: { debug: '*' } },
      'node_modules/express/node_modules/debug': { version: '2.6.9' },
    }
  });

  const pkgs = LP.parsePackageLockJson(fixture);

  test('skips root entry', () => expect(names(pkgs)).not.toContain(''));
  test('finds lodash',   () => expect(pkg(pkgs, 'lodash')).toBeDefined());
  test('finds express',  () => expect(pkg(pkgs, 'express')).toBeDefined());
  test('lodash version', () => expect(pkg(pkgs, 'lodash').version).toBe('4.17.21'));
  test('express version',() => expect(pkg(pkgs, 'express').version).toBe('4.18.2'));
  test('ecosystem npm',  () => expect(pkg(pkgs, 'lodash').ecosystem).toBe('npm'));
  test('express deps include lodash', () => expect(pkg(pkgs, 'express').deps).toContain('lodash'));
  test('peerDep included in deps', () => expect(pkg(pkgs, 'express').deps).toContain('debug'));
  test('nested node_modules parsed (debug)', () => expect(pkg(pkgs, 'debug')).toBeDefined());
  test('invalid JSON returns []', () => expect(LP.parsePackageLockJson('not json')).toEqual([]));
  test('empty packages returns []', () => expect(LP.parsePackageLockJson(JSON.stringify({ lockfileVersion: 2, packages: { '': {} } }))).toEqual([]));
});

// ─────────────────────────────────────────────────────────────────────────────
// yarn.lock v1
// ─────────────────────────────────────────────────────────────────────────────
describe('parseYarnLockV1', () => {
  const fixture = `# THIS IS AN AUTOGENERATED FILE.
# DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

lodash@^4.0.0, lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-abc==

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.npmjs.org/express/-/express-4.18.2.tgz"
  dependencies:
    lodash "^4.0.0"
    debug "^2.0.0"

debug@^2.0.0:
  version "2.6.9"
`;

  const pkgs = LP.parseYarnLockV1(fixture);

  test('finds lodash',    () => expect(pkg(pkgs, 'lodash')).toBeDefined());
  test('finds express',   () => expect(pkg(pkgs, 'express')).toBeDefined());
  test('finds debug',     () => expect(pkg(pkgs, 'debug')).toBeDefined());
  test('lodash version',  () => expect(pkg(pkgs, 'lodash').version).toBe('4.17.21'));
  test('express version', () => expect(pkg(pkgs, 'express').version).toBe('4.18.2'));
  test('debug version',   () => expect(pkg(pkgs, 'debug').version).toBe('2.6.9'));
  test('deduped — lodash appears once', () => expect(pkgs.filter(p => p.name === 'lodash').length).toBe(1));
  test('express deps',    () => expect(pkg(pkgs, 'express').deps).toContain('lodash'));
  test('express dep debug', () => expect(pkg(pkgs, 'express').deps).toContain('debug'));
  test('ecosystem npm',   () => expect(pkg(pkgs, 'lodash').ecosystem).toBe('npm'));
});

describe('parseYarnLock dispatches v1', () => {
  test('plain yarn.lock treated as v1', () => {
    const r = LP.parseYarnLock('lodash@^4.0.0:\n  version "4.17.21"\n');
    expect(r.length).toBeGreaterThan(0);
  });
});

describe('parseYarnLock dispatches v2', () => {
  const fixture = `__metadata:
  version: 6

"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: abc

"express@npm:^4.18.0":
  version: 4.18.2
  resolution: "express@npm:4.18.2"
  dependencies:
    lodash: "npm:^4.17.0"
`;
  test('detects v2 by __metadata', () => {
    const r = LP.parseYarnLock(fixture);
    expect(r.some(p => p.name === 'lodash')).toBe(true);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// poetry.lock
// ─────────────────────────────────────────────────────────────────────────────
describe('parsePoetryLock', () => {
  const fixture = `[[package]]
name = "requests"
version = "2.28.0"
description = "Python HTTP for Humans."
category = "main"
optional = false
python-versions = ">=3.7"

[package.dependencies]
certifi = ">=2017.4.17"
charset-normalizer = ">=2,<4"

[[package]]
name = "certifi"
version = "2023.5.7"
description = "Mozilla CA bundle."
category = "main"
optional = false
python-versions = ">=3.6"

[metadata]
lock-version = "1.1"
`;

  const pkgs = LP.parsePoetryLock(fixture);

  test('finds requests',           () => expect(pkg(pkgs, 'requests')).toBeDefined());
  test('finds certifi',            () => expect(pkg(pkgs, 'certifi')).toBeDefined());
  test('requests version',         () => expect(pkg(pkgs, 'requests').version).toBe('2.28.0'));
  test('certifi version',          () => expect(pkg(pkgs, 'certifi').version).toBe('2023.5.7'));
  test('ecosystem pypi',           () => expect(pkg(pkgs, 'requests').ecosystem).toBe('pypi'));
  test('requests deps include certifi', () => expect(pkg(pkgs, 'requests').deps).toContain('certifi'));
  test('certifi has no deps',      () => expect(pkg(pkgs, 'certifi').deps).toHaveLength(0));
  test('empty string returns []',  () => expect(LP.parsePoetryLock('')).toHaveLength(0));
});

// ─────────────────────────────────────────────────────────────────────────────
// Cargo.lock
// ─────────────────────────────────────────────────────────────────────────────
describe('parseCargoLock', () => {
  const fixture = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.160"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb2f3770"

[[package]]
name = "tokio"
version = "1.28.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "serde 1.0.160 (registry+https://github.com/rust-lang/crates.io-index)",
 "bytes",
]

[[package]]
name = "bytes"
version = "1.4.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

  const pkgs = LP.parseCargoLock(fixture);

  test('finds serde',   () => expect(pkg(pkgs, 'serde')).toBeDefined());
  test('finds tokio',   () => expect(pkg(pkgs, 'tokio')).toBeDefined());
  test('finds bytes',   () => expect(pkg(pkgs, 'bytes')).toBeDefined());
  test('serde version', () => expect(pkg(pkgs, 'serde').version).toBe('1.0.160'));
  test('tokio version', () => expect(pkg(pkgs, 'tokio').version).toBe('1.28.0'));
  test('ecosystem cargo',() => expect(pkg(pkgs, 'serde').ecosystem).toBe('cargo'));
  test('tokio depends on serde', () => expect(pkg(pkgs, 'tokio').deps).toContain('serde'));
  test('tokio depends on bytes', () => expect(pkg(pkgs, 'tokio').deps).toContain('bytes'));
  test('serde has no deps', () => expect(pkg(pkgs, 'serde').deps).toHaveLength(0));
});

// ─────────────────────────────────────────────────────────────────────────────
// composer.lock
// ─────────────────────────────────────────────────────────────────────────────
describe('parseComposerLock', () => {
  const fixture = JSON.stringify({
    '_readme': ['Autogenerated'],
    'packages': [
      { name: 'symfony/console', version: 'v6.2.7', require: { 'symfony/string': '^6.0', 'php': '>=8.1' } },
      { name: 'psr/log', version: '3.0.0', require: {} },
    ],
    'packages-dev': [
      { name: 'phpunit/phpunit', version: '10.1.0', require: { 'psr/log': '^3.0', 'ext-dom': '*' } },
    ],
  });

  const pkgs = LP.parseComposerLock(fixture);

  test('finds symfony/console', () => expect(pkg(pkgs, 'symfony')).toBeDefined());
  test('finds psr/log',          () => expect(pkg(pkgs, 'psr/log')).toBeDefined());
  test('finds phpunit (dev)',     () => expect(pkg(pkgs, 'phpunit')).toBeDefined());
  test('symfony version strips v', () => expect(pkg(pkgs, 'symfony').version).toBe('6.2.7'));
  test('psr/log version',          () => expect(pkg(pkgs, 'psr/log').version).toBe('3.0.0'));
  test('ecosystem composer',       () => expect(pkg(pkgs, 'symfony').ecosystem).toBe('composer'));
  test('php excluded from deps',   () => expect(pkg(pkgs, 'symfony').deps).not.toContain('php'));
  test('ext-dom excluded from deps', () => expect(pkg(pkgs, 'phpunit').deps).not.toContain('ext-dom'));
  test('symfony/string in deps',   () => expect(pkg(pkgs, 'symfony').deps).toContain('symfony/string'));
  test('phpunit dep on psr/log',   () => expect(pkg(pkgs, 'phpunit').deps).toContain('psr/log'));
  test('invalid JSON returns []',  () => expect(LP.parseComposerLock('not json')).toEqual([]));
});

// ─────────────────────────────────────────────────────────────────────────────
// go.mod
// ─────────────────────────────────────────────────────────────────────────────
describe('parseGoMod', () => {
  const fixture = `module github.com/myorg/myapp

go 1.21

require (
\tgithub.com/gin-gonic/gin v1.9.0
\tgithub.com/stretchr/testify v1.8.3
)

require github.com/go-playground/validator/v10 v10.14.0 // indirect

// ignore this comment
`;

  const pkgs = LP.parseGoMod(fixture);

  test('finds gin',       () => expect(pkg(pkgs, 'gin')).toBeDefined());
  test('finds testify',   () => expect(pkg(pkgs, 'testify')).toBeDefined());
  test('finds validator', () => expect(pkg(pkgs, 'validator')).toBeDefined());
  test('gin version',     () => expect(pkg(pkgs, 'gin').version).toBe('v1.9.0'));
  test('testify version', () => expect(pkg(pkgs, 'testify').version).toBe('v1.8.3'));
  test('validator version',() => expect(pkg(pkgs, 'validator').version).toBe('v10.14.0'));
  test('ecosystem golang',() => expect(pkg(pkgs, 'gin').ecosystem).toBe('golang'));
  test('no module line',  () => expect(names(pkgs)).not.toContain('github.com/myorg/myapp'));
  test('go directive not parsed', () => expect(pkgs.every(p => p.name !== 'go')).toBe(true));
});

// ─────────────────────────────────────────────────────────────────────────────
// Gemfile.lock
// ─────────────────────────────────────────────────────────────────────────────
describe('parseGemfileLock', () => {
  const fixture = `GIT
  remote: https://github.com/rails/rails.git
  revision: abc
  specs:
    rails (7.0.4.3)
      railties (= 7.0.4.3)

GEM
  remote: https://rubygems.org/
  specs:
    rails (7.0.8)
      actionmailer (= 7.0.8)
      actionpack (= 7.0.8)
    actionmailer (7.0.8)
      actionpack (= 7.0.8)
    actionpack (7.0.8)
    rake (13.0.6)

PLATFORMS
  ruby

DEPENDENCIES
  rails (~> 7.0)
  rake
`;

  const pkgs = LP.parseGemfileLock(fixture);

  test('finds rails',        () => expect(pkg(pkgs, 'rails')).toBeDefined());
  test('finds actionmailer', () => expect(pkg(pkgs, 'actionmailer')).toBeDefined());
  test('finds rake',         () => expect(pkg(pkgs, 'rake')).toBeDefined());
  test('rails version',      () => expect(pkg(pkgs, 'rails').version).toBe('7.0.8'));
  test('rake version',       () => expect(pkg(pkgs, 'rake').version).toBe('13.0.6'));
  test('ecosystem gem',      () => expect(pkg(pkgs, 'rails').ecosystem).toBe('gem'));
  test('GIT section NOT parsed (different indentation)', () => {
    // rails from GIT section has different indentation; GEM section rails is 7.0.8
    const r = pkg(pkgs, 'rails');
    expect(r.version).toBe('7.0.8');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// isLockfile / detectAndParse
// ─────────────────────────────────────────────────────────────────────────────
describe('isLockfile', () => {
  test('package-lock.json → true', () => expect(LP.isLockfile('package-lock.json')).toBe(true));
  test('yarn.lock → true',         () => expect(LP.isLockfile('yarn.lock')).toBe(true));
  test('poetry.lock → true',       () => expect(LP.isLockfile('poetry.lock')).toBe(true));
  test('Cargo.lock → true',        () => expect(LP.isLockfile('Cargo.lock')).toBe(true));
  test('composer.lock → true',     () => expect(LP.isLockfile('composer.lock')).toBe(true));
  test('go.mod → true',            () => expect(LP.isLockfile('go.mod')).toBe(true));
  test('Gemfile.lock → true',      () => expect(LP.isLockfile('Gemfile.lock')).toBe(true));
  test('subdirectory path → true', () => expect(LP.isLockfile('apps/api/package-lock.json')).toBe(true));
  test('package.json → false',     () => expect(LP.isLockfile('package.json')).toBe(false));
  test('random.txt → false',       () => expect(LP.isLockfile('random.txt')).toBe(false));
  test('Cargo.toml → false',       () => expect(LP.isLockfile('Cargo.toml')).toBe(false));
  test('go.sum → false',           () => expect(LP.isLockfile('go.sum')).toBe(false));
  test('empty string → false',     () => expect(LP.isLockfile('')).toBe(false));
});

describe('detectAndParse', () => {
  test('package-lock.json dispatches correctly', () => {
    const json = JSON.stringify({ lockfileVersion: 2, packages: { 'node_modules/foo': { version: '1.0.0' } } });
    const r = LP.detectAndParse('path/to/package-lock.json', json);
    expect(r).not.toBeNull();
    expect(r[0].name).toBe('foo');
  });

  test('unknown file returns null', () => {
    expect(LP.detectAndParse('package.json', '{}')).toBeNull();
  });

  test('Cargo.lock dispatches correctly', () => {
    const r = LP.detectAndParse('Cargo.lock', '[[package]]\nname = "serde"\nversion = "1.0.0"\n');
    expect(r).not.toBeNull();
    expect(r[0].ecosystem).toBe('cargo');
  });
});
